version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./index.js:/usr/src/app/index.js
      - ./utils:/usr/src/app/utils
      - ./dist:/usr/src/app/dist